eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
server:
  port: 1004
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-client:
      path: /api-client/**
      serviceId: eureka-client
    api-consumer:
      path: /api-consume/**
      serviceId: service-consumer